<?php

function comboBoxHtml($label, $map, $selected_row_value, $size = 1) {
    $html = "<div class='combobox'>";
    $html .= "<select name='$label' size='$size'>";
    $html .= "<option value=>[clear selection]</option>\n";
    foreach ($map as $id => $object) {
        $selected = ($id === intval($selected_row_value)) ? 'selected' : '';
        $html .= "<option value='$id' $selected>[$id] $object</option>\n";
    }
    $html .= "</select>\n";
    $html .= "</div>";
    return $html;
}

function detailsTableHtml($object, $fields) {
    $html = "<table class='details-table'><tbody>";
    foreach ($fields as $name => $config) {
        // draw label
        $html .= "<tr><th><label for='$name'>$name</label></th><td>";

        // collect configuration parameters for this field
        $f = array();
        foreach (array('control' => 'input', 'type' => 'text', 'form_name' => $name, 'value' => set_value($name, find($object, $name)), 'display' => '', 'options' => '') as $key => $default) {
            $f[$key] = isset($config[$key]) ? $config[$key] : $default;
        }

        // draw error
        $html .= form_error($name);
        // draw field
        if ($f['control'] === 'textarea') {
            $html .= "<textarea name='{$f['form_name']}'>{$f['value']}</textarea>";
        } else if ($f['control'] === 'radio') {
            foreach ($f['options'] as $value) {
                $checked = (find($object, $name) === $value) ? 'checked' : '';
                $html .= "<input class='radio' type='radio' name='{$f['form_name']}' value='$value' $checked >$value";
            }
        } else {
            $placeholder = ($f['type'] === 'date') ? "placeholder='yyyy-mm-dd'" : '';
            $html .= "<input type='{$f['type']}' class='{$f['type']}' name='{$f['form_name']}' value='{$f['value']}' $placeholder >{$f['display']}";
        }
        $html .= "</td></tr>";
    }
    $html .= "</tbody></table>";
    return $html;
}

function find(&$object, $field) {
    if (isset($object)) {
        return $object->$field;
    } else if (isset($user_data) && isset($user_data->$field)) {
        // from session variable
        return $user_data->$field;
    } else {
        return null;
    }
}

$TEST_FIELDS = array(
    'id' => array(
//        'form_name' => 'testId',
        'type' => 'hidden',
        'display' => find($selected_test, 'id') ? find($selected_test, 'id') : '<small>[autogenerated]</small>'),
    'title' => array(
        'control' => 'textarea'),
    'steps' => array(
        'control' => 'textarea'),
    'expectedResult' => array(
        'control' => 'textarea'),
    'creator' => array(),
    'creationDate' => array('type' => 'date')
);

$RESULT_FIELDS = array(
    'id' => array(
//        'form_name' => 'resultId',
        'type' => 'hidden',
        'display' => find($selected_result, 'id') ? find($selected_result, 'id') : '<small>[autogenerated]</small>'),
    'testId' => array(
        'type' => 'hidden',
        'value' => find($selected_test, 'id'),
        'display' => find($selected_test, 'id')),
    'date' => array(
        'type' => 'date'),
    'tester' => array(),
    'operatingSystem' => array(),
    'build' => array(),
    'result' => array(
        'control' => 'radio',
        'options' => array('pass', 'fail')),
    'comment' => array(
        'control' => 'textarea')
);
?>

<h1><?php echo $title ?></h1>
<table>
    <col style="width: 50%;">
    <col style="width: 50%;">
    <tr>
        <td>
            <form action='' method='get'>
                <?php echo comboBoxHtml('testId', $tests, (isset($selected_test) ? $selected_test->id : null), 10); ?>
            </form>
            <div class='detail'>
                <h2><?php echo isset($selected_test) ? $selected_test->pretty_print() : 'New Test' ?></h2>
                <form action='' method="post">
                    <?php echo detailsTableHtml($selected_test, $TEST_FIELDS); ?>
                    <input type='submit' name='submit_test_edit' 
                           value="<?php echo isset($selected_test) ? 'Update Test' : 'Create Test' ?>">
                           <?php if (isset($selected_test)) { ?>
                        <input type="submit" name='submit_test_delete' value="<?php echo 'Delete Test' ?>" >
                    <?php } ?>
                </form>
        </td>

        <?php if (isset($selected_test)) { ?>
            <td>
                <form action='' method="get">
                    <input type="hidden" name="testId" value="<?php echo $selected_test->id ?>">
                    <?php echo comboBoxHtml('resultId', $test_results, (isset($selected_result) ? $selected_result->id : null), 10); ?>
                </form>
                <div class='detail'>
                    <h2 class='form-heading'><?php echo isset($selected_result) ? $selected_result->pretty_print() : 'New test result' ?></h2>
                    <form action='' method="post">
                        <?php echo detailsTableHtml($selected_result, $RESULT_FIELDS) ?>
                        <input type='submit' name='submit_result_edit'
                               value="<?php echo isset($selected_result) ? 'Update Test Result' : 'Create Test Result' ?>">
                               <?php if (isset($selected_result)) { ?>
                            <input type="submit" name='submit_result_delete' value="<?php echo 'Delete Test Result' ?>" >
                        <?php } ?>
                    </form>
                </div>
            </td>
        <?php } ?>
    </tr>
</table>


<script src="<?php echo base_url('assets/js/jquery.min.js'); ?>"></script>
<script src="<?php echo base_url('assets/js/formacceleration.js'); ?>"></script>

